//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ChildComments = new HashSet<Comment>();
            this.CommentVotes = new HashSet<CommentVote>();
        }
    
        public int CommentID { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> ParentCommentID { get; set; }
        public string Text { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public int Upvotes { get; set; }
        public int Downvotes { get; set; }

        public int totalVotes()
        {
            return Upvotes - Downvotes;
        }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> ChildComments { get; set; }
        public virtual Comment ParentComment { get; set; }
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentVote> CommentVotes { get; set; }
        public int userVote { get; internal set; }
    }
}
