//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fitnessEntities : DbContext
    {
        public fitnessEntities()
            : base("name=fitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AerobicExercise> AerobicExercises { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<ExerciseList> ExerciseLists { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<StrengthExercise> StrengthExercises { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
