//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodIntake
    {
        public int UserID { get; set; }
        public int FoodID { get; set; }
        [Display(Name ="Date Recorded")]
        public System.DateTime DateRecorded { get; set; }
        public decimal Servings { get; set; }
        public int FoodIntakeID { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
    }
}
