//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.FoodIntakes = new HashSet<FoodIntake>();
        }
    
        public int FoodID { get; set; }
        public string Name { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Calories { get; set; }
        public Nullable<decimal> CaloriesFromFat { get; set; }
        public Nullable<decimal> SaturatedFat { get; set; }
        public Nullable<decimal> Cholestoral { get; set; }
        public Nullable<decimal> Sodium { get; set; }
        public Nullable<decimal> Potassium { get; set; }
        public Nullable<decimal> TotalCarbohydrate { get; set; }
        public Nullable<decimal> DietaryFiber { get; set; }
        public Nullable<decimal> Sugars { get; set; }
        public Nullable<decimal> Protein { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodIntake> FoodIntakes { get; set; }
    }
}
