//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Measurement
    {
        public int MeasurementID { get; set; }
        public int UserID { get; set; }
        [Display(Name = "Inches")]
        public decimal Value { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date Recorded")]
        public System.DateTime DateRecorded { get; set; }
        public int PartID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Part Part { get; set; }
    }
}
