//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int MeasurementID { get; set; }
        public int UserID { get; set; }
        public decimal Value { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public int PartID { get; set; }
    
        public virtual User User { get; set; }
        public virtual Part Part { get; set; }
    }
}
