//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StrengthExercise
    {
        public int ExerciseID { get; set; }
        public int UserID { get; set; }
        public int Rep { get; set; }
        public int Sets { get; set; }
        public int Weight { get; set; }
        public System.DateTime DateRecorded { get; set; }
        public int ExerciseListID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ExerciseList ExerciseList { get; set; }
    }
}
