//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeightExercise
    {
        public int ExerciseID { get; set; }
        public int Rep { get; set; }
        public int Sets { get; set; }
        public int Weight { get; set; }
    
        public virtual Exercise Exercise { get; set; }
    }
}
